CPPC = g++
CPPFLAGS = -std=c++17
#CPPFLAGS = -Wall -Werror

all: LeetcodeCompilation

LeetcodeCompilation: main.cpp ArrayAndHashing.cpp ArrayAndHashingTester.cpp Backtracking.cpp BacktrackingTester.cpp BinarySearch.cpp BinarySearchTester.cpp BitManipulation.cpp  BitManipulationTester.cpp DynamicProgramming.cpp DynamicProgrammingTester.cpp Graph.cpp GraphTester.cpp Greedy.cpp GreedyTester.cpp HeapAndPriorityQueue.cpp HeapAndPriorityQueueTester.cpp Intervals.cpp IntervalsTester.cpp LinkedList.cpp LinkedListTester.cpp MathAndGeometry.cpp MathAndGeometryTester.cpp SlidingWindow.cpp SlidingWindowTester.cpp Stack.cpp StackTester.cpp Tester.cpp TestRunner.cpp Tree.cpp TreePrinter.cpp TreeTester.cpp Trie.cpp TrieTester.cpp TwoPointers.cpp TwoPointersTester.cpp
	$(CPPC) $(CPPFLAGS) main.cpp ArrayAndHashing.cpp ArrayAndHashingTester.cpp Backtracking.cpp BacktrackingTester.cpp BinarySearch.cpp BinarySearchTester.cpp BitManipulation.cpp BitManipulationTester.cpp DynamicProgramming.cpp DynamicProgrammingTester.cpp Graph.cpp GraphTester.cpp Greedy.cpp GreedyTester.cpp HeapAndPriorityQueue.cpp HeapAndPriorityQueueTester.cpp Intervals.cpp IntervalsTester.cpp LinkedList.cpp LinkedListTester.cpp MathAndGeometry.cpp MathAndGeometryTester.cpp SlidingWindow.cpp SlidingWindowTester.cpp Stack.cpp StackTester.cpp Tester.cpp TestRunner.cpp Tree.cpp TreePrinter.cpp TreeTester.cpp Trie.cpp TrieTester.cpp TwoPointers.cpp TwoPointersTester.cpp -o LeetcodeCompilation -lm

clean:
	rm -f LeetcodeCompilation
